name: Debug Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: |
            app/src/main/go/v2ray-plugin/go.sum

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: generate local.properties
        run: |
          echo "storePassword=$KEYSTORE_PASS" >> local.properties
          echo "keyPassword=$KEY_PASS" >> local.properties
          echo "keyAlias=$KEY_ALIAS_NAME" >> local.properties

      - name: build with Gradle
        run: ./gradlew assembleDebug check

      - name: rename apks
        run: |
          cd app/build/outputs/apk/debug/
          for name in *.apk
          do
            newname=v2ray-plugin"$(echo "$name" | cut -c4-)"
            mv "$name" "$newname"
          done
          cd -

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            app/build/outputs/apk/debug/*
