name: Release Android CI

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number (e.g. 1.3.7)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: |
            app/src/main/go/v2ray-plugin/go.sum

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build with Gradle
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS_NAME: ${{ secrets.KEY_ALIAS_NAME }}
          KEY_PASS: ${{ secrets.KEY_PASS }}

        run: |
          echo "storePassword=$KEYSTORE_PASS" >> local.properties
          echo "keyPassword=$KEY_PASS" >> local.properties
          echo "keyAlias=$KEY_ALIAS_NAME" >> local.properties
          ./gradlew assembleRelease

      - name: rename apks
        run: |
          cd app/build/outputs/apk/release/
          for name in *.apk
          do
            newname=v2ray-plugin"$(echo "$name" | cut -c4-)"
            mv "$name" "$newname"
          done
          cd -

      - name: make release
        uses: softprops/action-gh-release@master
        with:
          fail_on_unmatched_files: true
          name: v2ray-plugin-android v${{ github.event.inputs.version_number }}
          tag_name: v${{ github.event.inputs.version_number }}
          files: |
            app/build/outputs/apk/release/*.apk
